### ISSUE TITLE
AdvancedFrame round corners not working

### ISSUE THREAD

**Issue by LeoJHarris** [XAM-Consulting/FreshEssentialsSample#12]
Hi seems like your advanced frame corners is not quite working properly setting this in xaml is just making a hard edge corners rectangle (taken from from samplecode):

```
<freshEssentials:AdvancedFrame Corners="all" CornerRadius="30" InnerBackground="Gold" OutlineColor="Red" HorizontalOptions="Center" WidthRequest="200">
                  <Label Text="Corners is All CornerRadius is 30" />
              </freshEssentials:AdvancedFrame>
```

**Comment by jessejiang0214** [comment]
In which platform iOS or Android?

**Comment by LeoJHarris** [comment]
android, 5.1.1 to be exact and I am using xamarin.forms 2.3.4.247 and freshessentials 2.1.3

**Comment by rodwin** [comment]
Same here. Radius is not working

**Comment by michelmoorlag** [comment]
Same problem here. A temporary workaround is to set the corner radius in code behind.
