### ISSUE TITLE
BindablePicker not working with asynchronous lists

### ISSUE THREAD

**Issue by chosenonehacks** [XAM-Consulting/FreshEssentialsSample#2]
Hi @rid00z 

When I am trying to bind BindablePicker ItemSource to list that is propagated from asynchronous call I never gets elements into picker list. Just zero instead of elements. When I bind to normal list without await it works.

I am not getting any exception, only what I see is below from Debug window.

'04-26 19:46:37.430 W/EGL_xap ( 4223): eglSurfaceAttrib not implemented
04-26 19:46:37.430 W/OpenGLRenderer( 4223): Failed to set EGL_SWAP_BEHAVIOR on surface 0x9a6a5800, error=EGL_SUCCESS`

Do you have any ideas?

**Comment by rid00z** [comment]
Can you send over a sample project with a reproduction?

**Comment by Ebsan** [comment]
@xorch Just a hunch, but have you tried setting the binding mode to TwoWay?

`ItemsSource="{Binding Projects, Mode=TwoWay}"`

**Comment by chosenonehacks** [comment]
@WiteCastle No, I haven't I switched over to XLabs version, as I was short on time, but you can have right.

**Comment by jessejiang0214** [comment]
This should be fixed in 2.1.2. Can you update FreshEssential and try again?
