### ISSUE TITLE
Required add LongTapped command!

### ISSUE THREAD

**Issue by huangjinshe** [XAM-Consulting/FreshEssentialsSample#5]
`<ListView ItemsSource="{Binding MyCars}" fe:ListViewItemLongTappedAttached.Command="{Binding ItemTapCommand}" fe:ListViewItemLongTappedSeconds="1.2">`

This example show us the command will execute if long press(more than 1.2 seconds) and release the listviewitem.

**Comment by jessejiang0214** [comment]
We cannot do that. In Android and UWP long press will show the context actions, 
https://developer.xamarin.com/guides/xamarin-forms/user-interface/listview/interactivity/#Context_Actions

It cannot work with iOS
