### ISSUE TITLE
AdvancedFrameRenderediOS not always working for SegmentedButtonGroup

### ISSUE THREAD

**Issue by Troto** [XAM-Consulting/FreshEssentialsSample#7]
I have an issue when deploying on the iPhone that sometimes a segmented button won't display correctly and will only show the text of one of the two buttons I have in the group and no border. It's the same display issue I was having when I forgot to call new advanced frame renderer. I have since added that call in appdelegate. Other segmented button groups on the page look fine but one will be incorrectly displayed.

**Comment by jessejiang0214** [comment]
So the issue still exist?

**Comment by Troto** [comment]
I honestly have no idea. I'm not even working on that project anymore, the code has probably been changed/moved/replaced.
