### ISSUE TITLE
How to change content on clicked selected index segmented button ?

### ISSUE THREAD

**Issue by Jaymeet** [XAM-Consulting/FreshEssentialsSample#9]
Hi... guess,
I have taken a Label content below the segmented button.
I would like to change label name on clicked particular segmented button with selected index.

I write a code, below..
in xaml..
 <StackLayout Margin="0,50,0,0">
                <fe:SegmentedButtonGroup
                    x:Name="SegGroup"  IsEnabled="True" OffColor="White" OnColor="Gray"
                    SelectedIndex="{Binding SelectIndex, Mode=OneWay}">
                    <fe:SegmentedButtonGroup.SegmentedButtons>
                        <fe:SegmentedButton Title="Top Brands" />
                        <fe:SegmentedButton Title="Near by Offers" />
                        <fe:SegmentedButton Title="Local" />
                        <fe:SegmentedButton Title="Brands" />
                        <fe:SegmentedButton Title="New to Push" />
                        <fe:SegmentedButton Title="Cataegories" />
                    </fe:SegmentedButtonGroup.SegmentedButtons>
                </fe:SegmentedButtonGroup>
            </StackLayout>

<StackLayout Margin="0,100,0,0">
                <Label x:Name="ValueLabel" />
            </StackLayout>

And In Xaml.cs

 void SelectIndex(object sender, EventArgs args)
        {
            switch (segmentGroup.SelectedIndex)
           {
               case 0:
                 ValueLabel.Text = "Top Brands";
                break;
             case 1:
                 ValueLabel.Text = "Near by Offers ";
                break;
              case 2:
                 ValueLabel.Text = "Local ";
                  break;
}
}

But its not changing content of label.
So what should do for changing label?

**Comment by jessejiang0214** [comment]
We don't design for changing title. But SegmentedButtonGroup class code is all in PCL, you can modify in your project to change the text of labels.
